<?php
namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function registerNewOne($data)
	{
		$username = $data['username'];
		$em = $this->getEntityManager();
		$check = $em
			->createQuery('SELECT COUNT(u) FROM AppBundle:User u WHERE u.username = :username')
			->setParameter('username', $username)
			->getSingleScalarResult();
		if (intval($check) == 0) {
			unset($data['username']);
			$user = User::createFromPayload($username, $data);
			$em->persist($user);
			$em->flush($user);
		} else {
			throw new \Exception(sprintf('User with username %s already exists.', $username), 1);
		}
		return $user;
	}
}
